db:
  uri: "mongodb://localhost:27017"
  database: "crawler_db"

logic:
  delay_between_requests: [0.8, 1.8]
  revisit_interval: 86400          # раз в сутки переобкачка
  batch_size: 10
  error_retry_interval: 3600       # если ошибка сети — повтор через час
  http_timeout: 15
  idle_sleep_seconds: 5
  user_agent: "EgorSearchCrawler/1.0 (lab2)"

crawl:
  parse_links_on_200: true
  max_discovered_per_page: 200

  global_deny:
    - "logout"
    - "register"
    - "login"
    - "captcha"
    - "\\.(jpg|jpeg|png|gif|webp|svg|pdf|zip|rar)$"

  rules:
    - source: "povarenok.ru"
      domains: ["www.povarenok.ru", "povarenok.ru"]
      allow:
        - "^https?://(www\\.)?povarenok\\.ru/recipes/show/\\d+/?$"

    - source: "koolinar.ru"
      domains: ["www.koolinar.ru", "koolinar.ru"]
      allow:
        - "^https?://(www\\.)?koolinar\\.ru/recipe/view/\\d+/?$"

seeds:
  urls: []

  meta_jsonl:
    - "../1/recipes_corpus/povarenok/meta/meta.jsonl"
    - "../1/recipes_corpus/koolinar/meta/meta.jsonl"